# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project.Canvasboard is an interactive board with plugins focusing on replacing the need of multiple platforms for teaching, presenting or explaining your ideas. The interactive plugins are built using web technologies to ease your work right within a single platform.
  Please adhere to our [Code of Conduct](https://github.com/Canvasbird/canvasboard/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/Canvasbird/canvasboard/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
  If you want to report a bugğŸ please follow our [Issue Template](https://github.com/Canvasbird/canvasboard/tree/master/.github/ISSUE_TEMPLATE). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  
  
  Feel free to join our [Slack Community](https://join.slack.com/t/canvasbird-workspace/shared_invite/zt-jjdml591-~SsL4vdSX9Mc_GUVIvYV7g).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨ Canvasboard is an interactive board with plugins focusing on replacing the need of multiple platforms for teaching, presenting or explaining your ideas. The interactive plugins are built using web technologies to ease your work right within a single platform.
  Please adhere to our [Code of Conduct](https://github.com/Canvasbird/canvasboard/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  Feel free to join our [Slack Community](https://join.slack.com/t/canvasbird-workspace/shared_invite/zt-jjdml591-~SsL4vdSX9Mc_GUVIvYV7g).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.

